version: "3.8"
services:
  grafana:
    image: grafana/grafana:8.1.3
    container_name: grafana
    depends_on:
      - loki
      - prometheus
    restart: unless-stopped
    expose:
      - 3000
    user: "0" # To allow Grafana to boot up
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=${DOMAIN}
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${SMTP_HOST}
      - GF_SMTP_USER=${SMTP_USER}
      - GF_SMTP_PASSWORD=${SMTP_PASS}
      - GF_SMTP_FROM_ADDRESS=${SMTP_FROM}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - monitoring
      - proxy
    links:
      - loki
      - prometheus
    labels:
      - traefik.enable=true

  prometheus:
    image: prom/prometheus:v2.29.2
    container_name: prometheus
    depends_on:
      - cadvisor
      - node-exporter
      - alertmanager
    restart: unless-stopped
    expose:
      - 9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    networks:
      - monitoring
    links:
      - cadvisor
      - node-exporter
      - alertmanager
    external_links:
      - traefik:traefik

  loki:
    image: grafana/loki:latest
    container_name: loki
    expose:
      - 3100
    volumes:
      - ./loki/loki.yml:/loki/etc/loki.conf
      - loki_data:/loki
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.2.2
    container_name: node-exporter
    restart: unless-stopped
    expose:
      - 9100
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
      - "--collector.systemd"
      - "--collector.processes"
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.6
    container_name: cadvisor
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:rw
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:v0.22.2
    container_name: alertmanager
    restart: unless-stopped
    expose:
      - 9093
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - monitoring

networks:
  proxy:
    external: true
  monitoring:
    name: monitoring

volumes:
  prometheus_data: {}
  loki_data: {}
  grafana_data: {}

